### ISSUE TITLE
AssertionError when trying to generate project

### ISSUE THREAD

**Issue by alexjlockwood** [kirjs/generator-d3-quickstart#3]
I get the below error when I follow the instructions specified in the `README.md`:

```
alex:~/blocks$ yo d3-quickstart project
events.js:182
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/alex/.nvm/versions/node/v8.1.1/lib/node_modules/generator-d3-quickstart/generators/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/Users/alex/.nvm/versions/node/v8.1.1/lib/node_modules/generator-d3-quickstart/node_modules/mem-fs-editor/actions/copy.js:44:3)
    at EditionInterface.exports.copy (/Users/alex/.nvm/versions/node/v8.1.1/lib/node_modules/generator-d3-quickstart/node_modules/mem-fs-editor/actions/copy.js:22:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/alex/.nvm/versions/node/v8.1.1/lib/node_modules/generator-d3-quickstart/node_modules/mem-fs-editor/actions/copy-tpl.js:9:8)
    at copy (/Users/alex/.nvm/versions/node/v8.1.1/lib/node_modules/generator-d3-quickstart/generators/app/index.js:13:26)
    at /Users/alex/.nvm/versions/node/v8.1.1/lib/node_modules/generator-d3-quickstart/generators/app/index.js:10:17
    at Array.forEach (native)
    at copy (/Users/alex/.nvm/versions/node/v8.1.1/lib/node_modules/generator-d3-quickstart/generators/app/index.js:9:22)
    at constructor.writing (/Users/alex/.nvm/versions/node/v8.1.1/lib/node_modules/generator-d3-quickstart/generators/app/index.js:52:9)
    at /Users/alex/.nvm/versions/node/v8.1.1/lib/node_modules/generator-d3-quickstart/node_modules/yeoman-generator/lib/base.js:409:16
    at runCallback (timers.js:800:20)
```

**Comment by alexjlockwood** [comment]
For some reason the directory contains only the following files:

```
alex:~$ ls -a /Users/alex/.nvm/versions/node/v8.1.1/lib/node_modules/generator-d3-quickstart/generators/app/templates
.		.npmignore	gulpfile.js	js
..		css		index.html	package.json
```

I was able to workaround the issue by manually adding a `.gitignore` file to the directory myself... but I'm not sure why it wasn't there to begin with.

**Comment by MovGP0** [comment]
confirmed. I have the same issue

**Comment by alogwe** [comment]
Having the same issue now. The file is there in the master branch that I cloned (screenshot) but I think the npm package must be out of date because it's not in the package that got installed. ![image](https://user-images.githubusercontent.com/774110/56393606-f61c0980-6202-11e9-90a4-3834e38bf7ea.png)
